linters:
  Comment:
    enabled: false

  LeadingZero:
    enabled: false

  NameFormat:
    convention: '^[a-z][-a-z0-9_]*$'

  MergeableSelector:
    force_nesting: false

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false

  SelectorDepth:
    enabled: false

  Shorthand:
    enabled: false

  StringQuotes:
    enabled: false

  VendorPrefix:
    enabled: false

  SelectorFormat:
    enabled: false

  QualifyingElement:
    enabled: false

  EmptyLineBetweenBlocks:
    enabled: false

  NestingDepth:
    enabled: false

  ImportantRule:
    enabled: false

  PropertyUnits:
    enabled: false

  IdSelector:
    enabled: false

  ColorVariable:
    enabled: false

  FinalNewline:
    enabled: false
